### ISSUE TITLE
Anyone can use the tool to make homes?!

### ISSUE THREAD

**Issue by Wiket123** [ExtReMLapin/gHomes#12]
Is this the case, I loaded into my server for the first time with GHomes on and I could immediately use the tool, no whitelisting or anything?!

**Comment by ExtReMLapin** [comment]
It's allowed for all superadmins

**Comment by ExtReMLapin** [comment]
https://github.com/ExtReMLapin/gHomes/blob/master/ghomes/lua/autorun/sh_exproperties.lua#L60
