### ISSUE TITLE
Only spawns props in home

### ISSUE THREAD

**Issue by expgamersinau** [ExtReMLapin/gHomes#15]
G'Day a long time ago you sent me to only allow players being able to spawn props inside there building (except admins) just wanting to get it fixed again thanks.
The code:
`local function propSpawn(ply, model)
    local foundhouse = 0

    for k, v in pairs(ghomes.list) do
        if ply:GetEyeTrace().HitPos:IsInHouse(k) then
            foundhouse = k

            if not ply:CanSpawnInHouse(k) then
                return false
            end
        end
    end

    if foundhouse == 0 then
        return false
    end
end

local function propSpawned(ply, model, ent)
    local foundhouse = 0

    for k, v in pairs(ghomes.list) do
        if ent:GetPos():IsInHouse(k) then
            foundhouse = k

            if not ply:CanSpawnInHouse(k) then
                return false
            end
        end
    end

    if foundhouse == 0 then
        return false
    end
end`

**Comment by ExtReMLapin** [comment]
Go here https://github.com/ExtReMLapin/gHomes/blob/master/ghomes/lua/ghomes_system/server/houses.lua#L93

Replace two functions by 

```Lua
local function propSpawn(ply, model)
	for k, v in ipairs(ghomes.list) do
		if ply:GetEyeTrace().HitPos:IsInHouse(k) then return ply:CanSpawnInHouse(k) end
	end

	return false
end

local function propSpawned(ply, model, ent)
	for k, v in ipairs(ghomes.list) do
		if ent:GetPos():IsInHouse(k) then return ply:CanSpawnInHouse(k) end
	end

	return false
end
```

**Comment by expgamersinau** [comment]
Doesn't seem to work?
