### ISSUE TITLE
Je ne vois pas le toolgun / I don't see the toolgun

### ISSUE THREAD

**Issue by ghost** [ExtReMLapin/gHomes#17]
Salut, je viens d'installer l'addon sur mon serveur, j'ai bien glissé le bon dossier dans le dossier "data"  mais quand je start mon serveur le toolgun n'est pas dans le SpawnMenu, peux-tu m'aider ?

(j'ai mit en anglais juste en bas pour les gens pas français qui ont le même problème)

Hi, I just installed the addon on my server, I dragged the right folder into the "data" folder but when I start my server the toolgun is not in the SpawnMenu, can you help me ?

**Comment by ghost** [comment]
Salut, donc je viens de trouver la solution, j'ai juste mit le mauvais dossier dans les addons, pensez bien à mettre le dossier "ghomes" et non "ghome-master" !

Hi, so I just found the solution, I just put the wrong folder in the addons, don't forget to put the "ghomes" folder and not "ghome-master"!

**Comment by ExtReMLapin** [comment]
pouet
