### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Sheppard26** [ExtReMLapin/gHomes#21]
je ne sais pas si je suis le seul mais je mets l'addon dans le dossier et rien ne marche alors que quand je l'avais y'a 1 ans tout marcher bien je suis le seul ?

**Comment by ExtReMLapin** [comment]
A l'heure actuelle, je serai surpris d'apprendre qu'il n'y a pas d'alternative.
Je sais que le "développeur moyen du darkrp" n'est pas le pingouin qui glisse le plus loin, ou du moins, c'était le cas il y a 6 ans, mais là ils ont eu le temps de sortir un addon de ce type, qui est maintenu et donc à jour avec un support.

Je ne joues plus à gmod depuis plusieurs années.

Le premier problème auquel je pense, c'est que sur linux, le nom du dossier (dans addon) doit être en minuscules (et sans tiret ?)

**Comment by Sheppard26** [comment]
meme si je mets tout en minuscule rien ne marche

**Comment by ExtReMLapin** [comment]
c la tristitud 😔

**Comment by ExtReMLapin** [comment]
Montre moi une screen du contenu du dossier et du contenu de ton dossier addons

Vérifies aussi qu'il n'y ai pas d'erreur dans ta console serveur

**Comment by Sheppard26** [comment]
![1](https://user-images.githubusercontent.com/132235517/235772841-ee49a375-3bda-4f9d-9078-1a616a92dd32.png)
![2](https://user-images.githubusercontent.com/132235517/235772842-d4a90ce8-1a49-4de2-b46c-c0d1d089a0b2.png)
![3](https://user-images.githubusercontent.com/132235517/235772844-5c136dca-b2ff-497c-97c9-8c97adb6f65d.png)

**Comment by ExtReMLapin** [comment]
grosse patate

**Comment by ExtReMLapin** [comment]
c'est "ghomes" que tu dois mettre dans addon, pas ghomes-master.

**Comment by Sheppard26** [comment]
C'est mieux xD merci
