### ISSUE TITLE
Error [entities/ghomes_suitcase/cl_init.lua:67]

### ISSUE THREAD

**Issue by Mika32150** [ExtReMLapin/gHomes#5]
[ERROR] addons/ghomes/lua/entities/ghomes_suitcase/cl_init.lua:67: attempt to index local 'tbl' (a nil value)
1. unknown - addons/ghomes/lua/entities/ghomes_suitcase/cl_init.lua:67

**Comment by ExtReMLapin** [comment]
It's an issue related to the model which can means


* You're using another model than the one provided with the workshop resources
* The resource(s) is/are missing on your client
