### ISSUE TITLE
Not returning money on leaving.

### ISSUE THREAD

**Issue by theepicsaxguy** [ExtReMLapin/gHomes#7]
With sell on leave enabled it does not return your 90% sell refund. This is in darkrp.

**Comment by theepicsaxguy** [comment]
Fix this and I love you for life.

**Comment by ExtReMLapin** [comment]
yo give me time dude

**Comment by ExtReMLapin** [comment]
Download this version and tell me if it's fixed : https://github.com/ExtReMLapin/gHomes/tree/fix-sell-on-leave

**Comment by theepicsaxguy** [comment]
That fixed it. You are a legend!
