### ISSUE TITLE
GHomes not working on Helix

### ISSUE THREAD

**Issue by Teskocf** [ExtReMLapin/gHomes#9]
I get this
[ERROR] addons/ghomes/lua/ghomes_system/client/dermabuddy.lua:67: attempt to concatenate a nil value
  1. confirmcreation - addons/ghomes/lua/ghomes_system/client/dermabuddy.lua:67
   2. leftclick - addons/ghomes/lua/weapons/gmod_tool/stools/enhanced_homes.lua:572
    3. v - addons/ghomes/lua/weapons/gmod_tool/stools/enhanced_homes.lua:590
     4. unknown - lua/includes/modules/hook.lua:84

befor the error i did a change to sh_compatibility/main.lua and returned at getCurGamemode() "ix"
because it everytime used the darkrp gamemode

**Comment by ExtReMLapin** [comment]
Well first, the issue is it was designed to work with players, not characters, it's based on steamID, not characters ID

I'll take a look at the error, but when reading the code it seems i did fuck something up

**Comment by Teskocf** [comment]
Okay is there a way that you could save it on character ID's ? Not SteamID's ? Would be very nice

**Comment by ExtReMLapin** [comment]
I edited the code, can you give another try ?

**Comment by ExtReMLapin** [comment]
For the identity thing i'll do something later

**Comment by Teskocf** [comment]
[ERROR] addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:47: attempt to call method 'isCP' (a nil value)
  1. canPlayerSpawnInHouse - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:47
   2. randomSpawn - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:55
    3. v - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:85
     4. unknown - lua/includes/modules/hook.lua:84

[WCD] »» No hotfixes applied
[WCD] »» Initiating player Teskocf
[LOG] Teskocf loaded the character 'Dean Tesko2'
1
1
1
gurken

[ERROR] addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:47: attempt to call method 'isCP' (a nil value)
  1. canPlayerSpawnInHouse - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:47
   2. randomSpawn - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:55
    3. v - addons/ghomes/lua/ghomes_system/dlcs/dlc1/server/sv_test.lua:85
     4. unknown - lua/includes/modules/hook.lua:84
      5. Spawn - [C]:-1
       6. func - gamemodes/helix/gamemode/core/libs/sh_character.lua:900
        7. unknown - lua/includes/extensions/net.lua:32


Should i temp. remove the DLC ?

**Comment by ExtReMLapin** [comment]
You can remove the DLC as you probably don't care about it, I forgot to implement isCP method to helix module

**Comment by ExtReMLapin** [comment]
you can remove the whole `dlcs` folder

**Comment by Teskocf** [comment]
[ERROR] addons/ghomes/lua/ghomes_system/sh_compatibility/darkrp.lua:98: attempt to call method 'setKeysNonOwnable' (a nil value)
  1. gHomeizeDoor - addons/ghomes/lua/ghomes_system/sh_compatibility/darkrp.lua:98
   2. generatedoors - addons/ghomes/lua/ghomes_system/server/houses.lua:30
    3. func - addons/ghomes/lua/ghomes_system/server/network.lua:332
     4. unknown - lua/includes/extensions/net.lua:32

When creating house

**Comment by Teskocf** [comment]
https://i.imgur.com/x50BFrs.png
and is it correct that i cant select new property ?

**Comment by ExtReMLapin** [comment]
in the server console do : 

`lua_run PrintTable(DarkRP)`

**Comment by Teskocf** [comment]
> PrintTable(DarkRP)...
formatMoney     =       function: 0x2ec7ab60

**Comment by ExtReMLapin** [comment]
Some shit ass addon developer is creating the darkrp table because he's a shit coder

**Comment by ExtReMLapin** [comment]
okay now do 

PrintTable(debug.getinfo(DarkRP.formatMoney))

**Comment by Teskocf** [comment]
currentline     =       -1
func    =       function: 0x2ec7ab60
isvararg        =       false
lastlinedefined =       4
linedefined     =       2
namewhat        =
nparams =       1
nups    =       0
short_src       =       addons/wcd/lua/wcd/wrapper/wcd_helix.lua
source  =       @addons/wcd/lua/wcd/wrapper/wcd_helix.lua
what    =       Lua

Williams Car dealer uff

**Comment by ExtReMLapin** [comment]
what a surprise

**Comment by Teskocf** [comment]
^^

**Comment by Teskocf** [comment]
To be honest i would do this in a config like you can select wrapper = "ix"

**Comment by ExtReMLapin** [comment]
If you legally downloaded this addon, be sure you have the latest version (i doubt he ever fixed this shit code), if you already do, get rid of it and all of his addons, he can't code shit.


>To be honest i would do this in a config like you can select wrapper = "ix"

The DarkRP table creation should not happen in the first place, you can code it yourself if you want or edit the code in [here](https://github.com/ExtReMLapin/gHomes/blob/master/ghomes/lua/ghomes_system/sh_compatibility/main.lua)

**Comment by Teskocf** [comment]
So i just return ix like last time ?

**Comment by ExtReMLapin** [comment]
just replace the func by 


```Lua
local function getCurGamemode()
    return "ix"
end
```

that's dirty but whatever

**Comment by Teskocf** [comment]
> 
> 
> https://i.imgur.com/x50BFrs.png
> and is it correct that i cant select new property ?

**Comment by Teskocf** [comment]
> 
> 
> [ERROR] addons/ghomes/lua/ghomes_system/sh_compatibility/darkrp.lua:98: attempt to call method 'setKeysNonOwnable' (a nil value)
> 
>     1. gHomeizeDoor - addons/ghomes/lua/ghomes_system/sh_compatibility/darkrp.lua:98
> 
>     2. generatedoors - addons/ghomes/lua/ghomes_system/server/houses.lua:30
>        3. func - addons/ghomes/lua/ghomes_system/server/network.lua:332
>        4. unknown - lua/includes/extensions/net.lua:32
> 
> 
> When creating house

Working !

**Comment by ExtReMLapin** [comment]
you should be able to left click to create new property btw

**Comment by Teskocf** [comment]
Ah nevermind i thought is was an other feature or something

Thanks for the fast and good support
